services:
  api: 
    build: .
    container_name: laser_craft_api
    ports:
      - 3333:3333
    depends_on:
      hivemq:
        condition: service_healthy
    environment:
      RUST_LOG: "error, info"
      API_HOST: ${API_HOST}
      MQTT_BROKER: ${MQTT_BROKER}
      MQTT_PASSWORD: ${MQTT_PASSWORD}
      MQTT_USER_NAME: ${MQTT_USER_NAME}
      MQTT_IMG_TOPIC: ${MQTT_IMG_TOPIC}
      MQTT_GCODE_TOPIC: ${MQTT_GCODE_TOPIC}
      MQTT_CLIENT_PREFIX: ${MQTT_CLIENT_PREFIX}
      MQTT_GCODE_NEXT_CHUNK_TOPIC: ${MQTT_GCODE_NEXT_CHUNK_TOPIC}
      MQTT_GCODE_NEXT_CHUNK_MESSAGE: ${MQTT_GCODE_NEXT_CHUNK_MESSAGE}
      GCODE_CHUNK_AMOUNT_LINES: ${GCODE_CHUNK_AMOUNT_LINES}
      IMG_TARGET_WIDTH: ${IMG_TARGET_WIDTH}
      IMG_TARGET_HEIGHT: ${IMG_TARGET_HEIGHT}
      GCODE_FEEDRATE: ${GCODE_FEEDRATE}

  hivemq:
    image: hivemq/hivemq4
    container_name: hivemq
    ports:
      - 8080:8080
      - 1883:1883
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:8080/ || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
