services:
  api: 
    build: .
    container_name: laser_craft_api
    ports:
      - 3333:3333
    environment:
      - API_HOST=${API_HOST}
      - MQTT_BROKER=${MQTT_BROKER}
      - MQTT_TOPIC=${MQTT_TOPIC}
      - MQTT_CLIENT_PREFIX=${MQTT_CLIENT_PREFIX}

  hivemq:
    image: hivemq/hivemq4
    container_name: hivemq
    ports:
      - 8080:8080
      - 1883:1883
